---
# tasks file for metiii.php
- name: Add the ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php'
- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: Install PHP
  apt: name={{item}} state=installed
  with_items:
   - php
   - php7.0-fpm
   - php7.0-mysql
   - php-xml
- name: Remove apache2
  apt: name=apache2 state=removed
