---
# tasks file for metiii.nginx
- name: Install nginx
  apt: name=nginx state=present
- name: Create nginx config
  template: src=templates/nginx/default dest=/etc/nginx/sites-available/default
  notify: restart nginx
