---
- name: do an apt-get update
  apt:
    update_cache: yes
- name: Install python
  apt:
    name: python2.7
    state: present
- name: Ensure that aptitude is installed
  apt:
    name: aptitude
    state: present
