---
# tasks file for metiii.mysql
- name: Install MySQL
  apt: name={{item}} state=installed
  with_items:
    - mysql-server-5.7
    - python-mysqldb
- name: Generate new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_pass
- name: Remove anonymous users
  mysql_user: name="" state=absent
  when: mysql_new_root_pass.changed
- name: Remove test database
  mysql_db: name=test state=absent
  when: mysql_new_root_pass.changed
- name: Output new root password
  debug: msg= "New root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed
- name: Update root password
  mysql_user: name=root password={{mysql_new_root_pass.stdout}}
  when: mysql_new_root_pass.changed
- name: Create my.cnf
  template: src=my.cnf dest=/root/.my.cnf
  when: mysql_new_root_pass.changed
